
name: Main Workflow

on: [push]

jobs:

    Build:
        runs-on: ubuntu-latest
        environment: TestEnv
        steps:
          
        - name: Setup .NET Core SDK 5.0.x
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: 5.0.x
          
        - uses: actions/checkout@v2
      
        - name: Restore Nuget
          run: dotnet restore
      
        - name: Build
          run: dotnet build --configuration Release --no-restore
        
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: testActionBuild
            path: TestWebApplication/bin/Release/net5.0
            retention-days: 1

    Container:
        runs-on: ubuntu-latest
        environment: TestEnv
        steps:      
      
        - name: Docker Build
          run: docker build . -t ghcr.io/jonnox0/actiontest:master
          
        - name: login with docker
          run: docker login ghcr.io -u jonnox0 -p ${{ secrets.Secret }}
      
        - name: register container
          run: docker image push ghcr.io/jonnox0/actiontest:master
          
        - name: docker logout
          run: docker logout
