name: Build Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
          dotnet-version: 5.0.x
          
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dir
      
    - name: docker build
      uses: docker/build-push-action@v2
      
    - name: register container
      run: |
        winpty echo $SECRET | docker login ghcr.io -u jonnox0 --password-stdin
        winpty docker image push ghcr.io/jonnox0/ActionTest1:latest

