
name: Main Workflow

on: [push]

jobs:

    Build:
        runs-on: ubuntu-latest
        environment: TestEnv
        steps:
      
        - name: login with docker
          run: docker login ghcr.io -u jonnox0 -p ${{ secrets.Secret }}
    
        - name: Setup .NET Core SDK 5.0.x
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: 5.0.x
          
        - uses: actions/checkout@v2
      
        - name: Install dependencies
          run: dotnet restore
      
        - name: Build
          run: dotnet build --configuration Release --no-restore
      
        - name: Docker build p
          run: docker build . -t ghcr.io/jonnox0/actiontest:master
        
        - name: docker images
          run: docker image list
      
        - name: register container
          run: docker image push ghcr.io/jonnox0/actiontest:master
        - name: docker logout
          run: docker logout
