name: Build Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build 
      run: docker build ./c# -t jonnox0/mytestcontainer
